
name: Render Deploy

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install dependencies and run tests
      - name: Install Dependencies and Test
        run: |
          npm install
          npm run test-component

      # Trigger Render Deploy Hook
      - name: Deploy to Render
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$DEPLOY_URL"